# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/age_groups', type: :request do
  # AgeGroup. As you add validations to AgeGroup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      AgeGroup.create! valid_attributes
      get age_groups_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      age_group = AgeGroup.create! valid_attributes
      get age_group_url(age_group)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_age_group_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      age_group = AgeGroup.create! valid_attributes
      get edit_age_group_url(age_group)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new AgeGroup' do
        expect do
          post age_groups_url, params: { age_group: valid_attributes }
        end.to change(AgeGroup, :count).by(1)
      end

      it 'redirects to the created age_group' do
        post age_groups_url, params: { age_group: valid_attributes }
        expect(response).to redirect_to(age_group_url(AgeGroup.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new AgeGroup' do
        expect do
          post age_groups_url, params: { age_group: invalid_attributes }
        end.to change(AgeGroup, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post age_groups_url, params: { age_group: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested age_group' do
        age_group = AgeGroup.create! valid_attributes
        patch age_group_url(age_group), params: { age_group: new_attributes }
        age_group.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the age_group' do
        age_group = AgeGroup.create! valid_attributes
        patch age_group_url(age_group), params: { age_group: new_attributes }
        age_group.reload
        expect(response).to redirect_to(age_group_url(age_group))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        age_group = AgeGroup.create! valid_attributes
        patch age_group_url(age_group), params: { age_group: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested age_group' do
      age_group = AgeGroup.create! valid_attributes
      expect do
        delete age_group_url(age_group)
      end.to change(AgeGroup, :count).by(-1)
    end

    it 'redirects to the age_groups list' do
      age_group = AgeGroup.create! valid_attributes
      delete age_group_url(age_group)
      expect(response).to redirect_to(age_groups_url)
    end
  end
end
