# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/indicator_medals', type: :request do
  # IndicatorMedal. As you add validations to IndicatorMedal, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      IndicatorMedal.create! valid_attributes
      get indicator_medals_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      indicator_medal = IndicatorMedal.create! valid_attributes
      get indicator_medal_url(indicator_medal)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_indicator_medal_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      indicator_medal = IndicatorMedal.create! valid_attributes
      get edit_indicator_medal_url(indicator_medal)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new IndicatorMedal' do
        expect do
          post indicator_medals_url, params: { indicator_medal: valid_attributes }
        end.to change(IndicatorMedal, :count).by(1)
      end

      it 'redirects to the created indicator_medal' do
        post indicator_medals_url, params: { indicator_medal: valid_attributes }
        expect(response).to redirect_to(indicator_medal_url(IndicatorMedal.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new IndicatorMedal' do
        expect do
          post indicator_medals_url, params: { indicator_medal: invalid_attributes }
        end.to change(IndicatorMedal, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post indicator_medals_url, params: { indicator_medal: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested indicator_medal' do
        indicator_medal = IndicatorMedal.create! valid_attributes
        patch indicator_medal_url(indicator_medal), params: { indicator_medal: new_attributes }
        indicator_medal.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the indicator_medal' do
        indicator_medal = IndicatorMedal.create! valid_attributes
        patch indicator_medal_url(indicator_medal), params: { indicator_medal: new_attributes }
        indicator_medal.reload
        expect(response).to redirect_to(indicator_medal_url(indicator_medal))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        indicator_medal = IndicatorMedal.create! valid_attributes
        patch indicator_medal_url(indicator_medal), params: { indicator_medal: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested indicator_medal' do
      indicator_medal = IndicatorMedal.create! valid_attributes
      expect do
        delete indicator_medal_url(indicator_medal)
      end.to change(IndicatorMedal, :count).by(-1)
    end

    it 'redirects to the indicator_medals list' do
      indicator_medal = IndicatorMedal.create! valid_attributes
      delete indicator_medal_url(indicator_medal)
      expect(response).to redirect_to(indicator_medals_url)
    end
  end
end
